modules/views.py
# Routes for users not logged in
from flask import (Blueprint, render_template, render_template_string, request, flash,redirect, url_for)
from flask_login import login_required, current_user

from . import db
from .models import Post, User, Comment

views = Blueprint("views", __name__)


# -------------------------
# -------------------------
# --------Home-Page--------
# -------------------------
# -------------------------

@views.route("/")
@views.route("/home")
@login_required
def home():
    posts = Post.query.all()
    return render_template("home.html", user=current_user, posts=posts)



# -------------------------
# -------------------------
# ------Create-Post--------
# -------------------------
# -------------------------

@views.route("/home", methods=["GET", "POST"])
@login_required
def create_post():
    if request.method == "POST":
        text = request.form.get("text")

        if not text:
            flash("Post cannot be empty", category="error")
        else:
            post = Post(text=text, author=current_user.id)
            db.session.add(post)
            db.session.commit()
            flash("Post created!", category="success")

    return redirect(url_for("views.home", user=current_user))



# -------------------------
# -------------------------
# ------Add-Comment--------
# -------------------------
# -------------------------

@views.route("/create-comment/<post_id>", methods=['POST'])
@login_required
def create_comment(post_id):
    text = request.form.get('text')

    if not text:
        flash('Comment cannot be empty.', category='error')
    else:
        post = Post.query.filter_by(id=post_id)
        if post:
            comment = Comment(
                text=text, author=current_user.id, post_id=post_id)
            db.session.add(comment)
            db.session.commit()
        else:
            flash('Post does not exist.', category='error')

    return redirect(url_for('views.home'))



# -------------------------
# -------------------------
# ------Remove-Comment-----
# -------------------------
# -------------------------

@views.route("/delete-comment/<comment_id>")
@login_required
def delete_comment(comment_id):
    comment = Comment.query.filter_by(id=comment_id).first()

    if not comment:
        flash('Comment does not exist.', category='error')
    elif current_user.id != comment.author and current_user.id != comment.post.author:
        flash('You do not have permission to delete this comment.', category='error')
    else:
        db.session.delete(comment)
        db.session.commit()

    return redirect(url_for('views.home'))











# -------------------------
# -------------------------
# -------Delete-Post-------
# -------------------------
# -------------------------

@views.route("/delete-post/<id>")
@login_required
def delete_post(id):
    post = Post.query.filter_by(id=id).first()

    if not post:
        flash("Post does not exist.", category="error")
    elif current_user.id != post.author:
        flash("You do not have permission to delete this post.", category="error")
    else:
        db.session.delete(post)
        db.session.commit()
        flash("Post deleted.", category="success")
    return redirect(url_for("views.home"))


# -------------------------
# -------------------------
# -----Profile--Page-------
# -------------------------
# -------------------------
@views.route("/user/<username>", methods=["GET", "POST"])
@login_required
def profile(username):

    #Allows user to create a post on their profile 
    create_post()

    #Checks if user exists
    user = User.query.filter_by(username=username).first()
    if not user:
        flash("User does not exist", category="error")
        return redirect(url_for("views.home"))
    
    #Grabs all the users posts 
    post = Post.query.filter_by(author=user.id).all()

    #Counts the number of posts the user has
    post_number = len(post)

    return render_template("user.html", user=current_user, username=username, posts=post, post_number=post_number)

modules/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!--External Links-->
    <!--Bootstrap-->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
    <!--Awesome Font for Icons-->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
    />

    <!--Internal Links-->
    <link rel="stylesheet" href="../static/style.css" />

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <!--Navbar-->
    <div class="navbar">
      <div class="logo">
        <i class="fa fa-solid fa-laptop-code"></i>Social Tech
      </div>
      <div class="menu">
        {% if current_user.is_authenticated %}
        <a href="/home"><i class="fas fa-home"></i> Home</a>
        <a href="{{ url_for('views.profile', username=current_user.username)}}"
          ><i class="fas fa-user"></i> Profile</a
        >
        <a href="#"><i class="fas fa-cog"></i> Settings</a>
        <a href="/logout"><i class="fas fa-sign-out-alt"></i> Logout</a>
        {% else %}
        <a href="/sign-up"><i class="fas fa-user-plus"></i> Sign Up</a>
        <a href="/login"><i class="fas fa-sign-in-alt"></i> Login</a>
        {% endif %}
      </div>
      <div class="search">
        <input type="text" placeholder="Search..." />
        <button title="Search"><i class="fas fa-search"></i></button>
      </div>
    </div>
    <!--Message Flashing-->
    {% with messages = get_flashed_messages(with_categories=True) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    "success" %}
    <div class="alert alert-success alter-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
    {% else %}
    <div class="alert alert-danger alter-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %} {% block content %}{%
    endblock %}
  </body>
</html>

modules/templates/home.html
{% extends "posts.html" %} {% block title %}Home{% endblock %}

modules/templates/login.html
{% extends "base.html" %} {% block title %}Home Page{% endblock %} {% block
content%}
<div class="container">
  <form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
      <label for="email">Email Address</label>
      <input
        type="text"
        id="email"
        name="email"
        class="form-control"
        placeholder="Enter your Email"
      />
      <label for="password1">Password</label>
      <input
        type="password"
        id="password1"
        name="password1"
        class="form-control"
        placeholder="Enter your Password"
      />
      <br />
      <div align="center">
        <button type="sub" class="btn btn-dark">Login</button>
      </div>
    </div>
  </form>
</div>
{% endblock %}

modules/templates/posts.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}
<div class="post-container">
  <h1 align="center">{% block header %}Home{% endblock %}</h1>
  <form method="POST">
    <div class="create-post">
      <textarea
        class="form-control"
        name="text"
        id="text"
        placeholder="What is happening {{user.username}}"
      ></textarea>
      <div class="create-post-footer">
        <div class="create-post-actions">
          <i
            class="create-post-icons fas fa-solid fa-image fa-lg"
            style="color: #000000"
          ></i>
          <i
            class="create-post-icons fas fa-regular fa-video fa-lg"
            style="color: #000000"
          ></i>
        </div>
        <button class="post-btn" type="submit">Post</button>
      </div>
    </div>
  </form>

  <!-- Individual Posts and Comments -->
  {% for post in posts %}
  <div class="post">
    <div class="post-header">
      <div class="post-icon">
        <a href="{{ url_for('views.profile', username=post.user.username)}}">
          <img src="../static/images/pp_pic.jpg" alt="Profile Picture" />
        </a>
      </div>
      <!-- Shows the username and content of the author -->
      <div class="username">{{post.user.username}}</div>

      <!-- Delete Button -->
      <div class="post-delete">
        {% if user.id == post.author %}
        <button
          type="button"
          class="btn btn-sm btn-dark dropdown-toggle"
          data-bs-toggle="dropdown"
        ></button>
        <ul class="dropdown-menu">
          <li>
            <a href="/delete-post/{{post.id}}" class="dropdown-item">Delete</a>
          </li>
        </ul>
        {% endif %}
      </div>
    </div>

    <div class="post-content">{{post.text}}</div>

    <div class="post-footer">
      <div class="actions">
        <div class="action-icon">Like</div>
        <div class="action-icon">Comment</div>
        <div class="action-icon">Share</div>
      </div>
      <div class="post-time">{{post.date_created}}</div>
    </div>

    <!--Creating Comments-->
    <div class="collapse" id="comments-{{post.id}}">
      <div class="comment">
        <div class="comment-body" id="comments-expanded-{{post.id}}">
          {% for comment in post.comments %}
          <div class="d-flex justify-content-between align-items-center">
            <div>
              <a href="/user/{{comment.user.username}}"
                >{{comment.user.username}}</a
              >: {{comment.text}}
            </div>
            <div>
              <small class="text-muted">{{comment.date_created}}</small>
              {% if user.id == comment.author or user.id == post.author %}
              <div class="btn-group">
                <button
                  type="button"
                  class="btn btn-sm btn-primary dropdown-toggle"
                  data-bs-toggle="dropdown"
                ></button>
                <ul class="dropdown-menu">
                  <li>
                    <a
                      href="/delete-comment/{{comment.id}}"
                      class="dropdown-item"
                      >Delete</a
                    >
                  </li>
                </ul>
              </div>
              {% endif %}
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>

    <p class="post-comment">
      {% if post.comments|length > 0 %}
      <a data-bs-toggle="collapse" href="#comments-{{post.id}}" role="button">
        <small>View {{post.comments|length}} Comments</small>
      </a>
      {% else %}
      <small class="text-muted">No Comments</small>
      {% endif %}
    </p>

    <form
      class="input-group mb-3"
      method="POST"
      action="/create-comment/{{post.id}}"
    >
      <input
        type="text"
        id="text"
        name="text"
        class="form-control"
        placeholder="Write a comment"
      />
      <button type="submit" class="btn btn-primary">Comment</button>
    </form>
  </div>
  {% endfor %} {% block footer %} {% endblock %}
</div>
{% endblock %}

modules/templates/signUp.html
{% extends "base.html" %} {% block title %}Home Page{% endblock %} {% block
content%}
<div class="container">
<form method="POST">
  <h3 align="center">Sign Up</h3>
  <div class="form-group">
    <label for="username">Username</label>
    <!--Name posts the data to our backend-->
    <input
      type="text"
      id="username"
      name="username"
      class="form-control"
      placeholder="@Username"
    />
    <label for="email">Email Address</label>
    <input
      type="text"
      id="email"
      name="email"
      class="form-control"
      placeholder="Enter your Email"
    />
    <label for="password1">Password</label>
    <input
      type="password"
      id="password1"
      name="password1"
      class="form-control"
      placeholder="Enter your Password"
    />
    <label for="password1">Password (Confirm)</label>
    <input
      type="password"
      id="password2"
      name="password2"
      class="form-control"
      placeholder="Enter your Password"
    />
    <br />
    <div align="center">
      <button class="btn btn-dark" type="submit">Sign Up</button>
    </div>
  </div>
</form>
{% endblock %}

modules/templates/sign_success.html
{% extends "base.html" %} {% block title %}sign-up-success{% endblock %} {%
block content%}
<h1>Success!</h1>
<p>Your account has been created</p>
<p>Go checkout the <a href="{{ url_for('views.home') }}">Home Page</p>
{% endblock %}

modules/templates/user.html
{% extends "posts.html" %}{% block title %}{{username}}{% endblock %} {% block
content %}
<title>Profile Page</title>
<body>
  <div class="profile-container">
    <div class="profile-banner">
      <img src="../static/images/background.jpg" alt="Profile Banner" />
    </div>
    <div class="profile-picture">
      <img src="../static/images/pp_pic.jpg" alt="Profile Picture" />
    </div>
    <div class="profile-header">
      <h1 class="profile-name">{{username}}</h1>
      <p class="profile-handle">@{{username}}</p>
    </div>
    <div class="profile-content">
      <p class="profile-bio">I like Cheese and Pickles</p>
      <ul class="profile-stats">
        <li>
          <span class="stat-label">Posts </span>
          <!--Shows the number of posts-->
          <span class="stat-value"> {{post_number}}</span>
        </li>
        <li>
          <span class="stat-label">Followers </span
          ><span class="stat-value">0</span>
        </li>
        <li>
          <span class="stat-label">Following </span
          ><span class="stat-value">0</span>
        </li>
      </ul>
    </div>
  </div>
</body>
</br>
<div class="post-container">
  <form method="POST">
    {% if current_user.username == username %}
    <div class="create-post">
      <textarea
        class="form-control"
        name="text"
        id="text"
        placeholder="What is happening, {{user.username}}!"
      ></textarea>
      
      <div class="create-post-footer">
        <div class="create-post-actions">
          <i
            class="create-post-icons fas fa-solid fa-image fa-lg"
            style="color: #000000"
          ></i>
          <i
            class="create-post-icons fas fa-regular fa-video fa-lg"
            style="color: #000000"
          ></i>
        </div>
        <button class="post-btn" type="submit">Post</button>
      </div>
      {% endif %}
    </div>
    <!--Creates the Individual Post-->
    {% for post in posts %}
    <div class="profile-container post">
      <div class="post-header">
        <div class="post-icon">
          <a href="{{ url_for('views.profile', username=post.user.username)}}">
            <img src="../static/images/pp_pic.jpg" alt="Profile Picture" />
          </div>
            <!--Shows the username and content of the author-->
            <div class="username">{{post.user.username}}</div>
          </a>
          <!--Delete Button-->
          <div class="post-delete">
            {% if user.id == post.author %}
            <button
              type="button"
              class="btn btn-sm btn-dark dropdown-toggle"
              data-bs-toggle="dropdown"
            ></button>
            <ul class="dropdown-menu">
              <li>
                <a href="/delete-post/{{post.id}}" class="dropdown-item"
                  >Delete</a
                >
              </li>
            </ul>
            {% endif %}
          </div>
        </div>
        <div class="post-content">{{post.text}}</div>
        <div class="post-footer">
          <div class="actions">
            <div class="action-icon">Like</div>
            <div class="action-icon">Share</div>
            <div class="action-icon">Comment</div>
          </div>
          <div class="post-time">{{post.date_created}}</div>
        </div>
      </div>
    </div>
    {% endfor %} {% block footer %} {% endblock %} {% endblock %}
  </form>
</div>